OK_STATUS = 200
BAD_REQUEST_STATUS = 400
FORBIDDEN_STATUS = 403
NOT_FOUND_STATUS = 404
METHOD_NOT_ALLOWED_STATUS = 405

STATUS_DESCRIPTION = {
    OK_STATUS: 'OK',
    BAD_REQUEST_STATUS: 'Bad Request',
    FORBIDDEN_STATUS: 'Forbidden',
    NOT_FOUND_STATUS: 'Not Found',
    METHOD_NOT_ALLOWED_STATUS: 'Method Not Allowed',
}
